// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pretpark.database;

#nullable disable

namespace database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221016193555_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("pretpark.database.models.Attractie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("attracties");
                });

            modelBuilder.Entity("pretpark.database.models.DateTimeBereik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Begin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Eind")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("dateTimeBereik");
                });

            modelBuilder.Entity("pretpark.database.models.GastInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LaatstBezochteURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("gastInfo");
                });

            modelBuilder.Entity("pretpark.database.models.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers", (string)null);
                });

            modelBuilder.Entity("pretpark.database.models.Onderhoud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Probleem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("aanAttractieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("aanAttractieId");

                    b.ToTable("ondehoud");
                });

            modelBuilder.Entity("pretpark.database.models.Reservering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AttractieId")
                        .HasColumnType("int");

                    b.Property<int>("GastId")
                        .HasColumnType("int");

                    b.Property<int?>("GedurendeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttractieId");

                    b.HasIndex("GastId");

                    b.HasIndex("GedurendeId");

                    b.ToTable("reservering");
                });

            modelBuilder.Entity("pretpark.database.models.Gast", b =>
                {
                    b.HasBaseType("pretpark.database.models.Gebruiker");

                    b.Property<int?>("BegeleiderId")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<DateTime>("EersteBezoek")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FavorietId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeboorteDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("gastInfoId")
                        .HasColumnType("int");

                    b.HasIndex("BegeleiderId")
                        .IsUnique()
                        .HasFilter("[BegeleiderId] IS NOT NULL");

                    b.HasIndex("FavorietId");

                    b.HasIndex("gastInfoId")
                        .IsUnique()
                        .HasFilter("[gastInfoId] IS NOT NULL");

                    b.ToTable("Gasten", (string)null);
                });

            modelBuilder.Entity("pretpark.database.models.Medewerker", b =>
                {
                    b.HasBaseType("pretpark.database.models.Gebruiker");

                    b.ToTable("Medewerkers", (string)null);
                });

            modelBuilder.Entity("pretpark.database.models.GastInfo", b =>
                {
                    b.OwnsOne("pretpark.database.models.Coordinate", "coordinate", b1 =>
                        {
                            b1.Property<int>("GastInfoId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<int>("X")
                                .HasColumnType("int");

                            b1.Property<int>("Y")
                                .HasColumnType("int");

                            b1.HasKey("GastInfoId");

                            b1.ToTable("coordinaat");

                            b1.WithOwner()
                                .HasForeignKey("GastInfoId");
                        });

                    b.Navigation("coordinate")
                        .IsRequired();
                });

            modelBuilder.Entity("pretpark.database.models.Onderhoud", b =>
                {
                    b.HasOne("pretpark.database.models.Attractie", "aanAttractie")
                        .WithMany()
                        .HasForeignKey("aanAttractieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aanAttractie");
                });

            modelBuilder.Entity("pretpark.database.models.Reservering", b =>
                {
                    b.HasOne("pretpark.database.models.Attractie", "Attractie")
                        .WithMany()
                        .HasForeignKey("AttractieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pretpark.database.models.Gast", "Gast")
                        .WithMany("reservering")
                        .HasForeignKey("GastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pretpark.database.models.DateTimeBereik", "Gedurende")
                        .WithMany()
                        .HasForeignKey("GedurendeId");

                    b.Navigation("Attractie");

                    b.Navigation("Gast");

                    b.Navigation("Gedurende");
                });

            modelBuilder.Entity("pretpark.database.models.Gast", b =>
                {
                    b.HasOne("pretpark.database.models.Gast", "Begeleider")
                        .WithOne("Begeleidt")
                        .HasForeignKey("pretpark.database.models.Gast", "BegeleiderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("pretpark.database.models.Attractie", "Favoriet")
                        .WithMany()
                        .HasForeignKey("FavorietId");

                    b.HasOne("pretpark.database.models.Gebruiker", null)
                        .WithOne()
                        .HasForeignKey("pretpark.database.models.Gast", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("pretpark.database.models.GastInfo", "gastInfo")
                        .WithOne("gast")
                        .HasForeignKey("pretpark.database.models.Gast", "gastInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Begeleider");

                    b.Navigation("Favoriet");

                    b.Navigation("gastInfo");
                });

            modelBuilder.Entity("pretpark.database.models.Medewerker", b =>
                {
                    b.HasOne("pretpark.database.models.Gebruiker", null)
                        .WithOne()
                        .HasForeignKey("pretpark.database.models.Medewerker", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pretpark.database.models.GastInfo", b =>
                {
                    b.Navigation("gast")
                        .IsRequired();
                });

            modelBuilder.Entity("pretpark.database.models.Gast", b =>
                {
                    b.Navigation("Begeleidt");

                    b.Navigation("reservering");
                });
#pragma warning restore 612, 618
        }
    }
}
